### ISSUE TITLE
There is no item named 'META-INF\\\\container.xml

### ISSUE THREAD

**Issue by tgeik** [aerkalov/ebooklib#162] opened 2018-07-24 16:01 UTC
Python 3.5.1 32bit.
Cannot read epub files with epub.read_epub. Even if the epub is created using the example in documentations, I still get: "There is no item named 'META-INF\\\\container.xml" in the archive"

**Comment by aerkalov** [comment] 2018-07-24 17:06
Hi! Can you maybe provide the EPUB file so I could test it? Are you maybe using Windows?

**Comment by tgeik** [comment] 2018-07-24 17:14
Yes, I'm using windows.
[Sample.zip](https://github.com/aerkalov/ebooklib/files/2224646/Sample.zip)

**Comment by aerkalov** [comment] 2018-07-25 22:53
Yeah, the problem is that ebooklib uses certain function calls like os.path.normpath to normalise the path but on the Windows machine it also changes directory separator used when working with ZipFile. ZipFile expects it to be "/" but normpath changes it to "\\". I don't have a Windows machine (I just installed it in the VirtualBox but I don't have Visual Studio to compile the lxml) of my own but will change it on a branch and let you test it :)

**Comment by aerkalov** [comment] 2018-08-07 20:13
Sorry this took way too long but this should be fixed now and the changes are in master branch. You can test it now. I tried it only on Windows with samples 01 (to create EPUB) and 06 (to parse existing EPUB).

**Comment by tgeik** [comment] 2018-08-18 10:42
Sorry it took me a while to test and reply. It works fine so far. Thanks for the quick response.

**Comment by aerkalov** [comment] 2018-08-18 14:04
Great! Will close this one for now.

**Closed by aerkalov** 2018-08-18 14:04 UTC

**Comment by jstruyf** [comment] 2018-09-03 07:54
I have the same error, everything works OK on OSX, but not in Window7 32bit (Have not tried windows 64bit yet). How can I get that new version? I run ebooklib version 0.17. Thanks

**Comment by aerkalov** [comment] 2018-09-03 10:33
Install latest version from GitHub until we do the release:

`pip install -e git+git://github.com/aerkalov/ebooklib.git#egg=EbookLib`

**Comment by jstruyf** [comment] 2018-09-03 11:51
Hi Aerkalov,

Many thanks for this. 
I guess I also can use that for OSX. 
Because I see that those directory + containers file are missing, but it did not give a error and did work OK. 

Best regards,
Jan

**Comment by axtrace** [comment] 2018-09-08 11:04
Great! I have the same problem and `pip install ebooklib `did not install the latest version. I tried what you've said and it helps! Thank you!
`pip install -e git+git://github.com/aerkalov/ebooklib.git#egg=EbookLib`

**Comment by aerkalov** [comment] 2019-01-02 23:52
@padmalcom What do you mean? Can you explain more.

**Comment by padmalcom** [comment] 2019-01-03 07:03
@aerkalov Hi Aleksandar, I mean that I still have to install ebooklib from git. When I install via pip and pypi I keep getting the error described above on windows.

**Comment by aerkalov** [comment] 2023-04-18 20:28
@Quemoy I have no experience with conda-forge but looking at it this would be the feedstock for the ebooklib and those Contributors would be the one who would know what to do - https://github.com/conda-forge/ebooklib-feedstock

Looking at the project I would assume it is required to update the version number and change the sha256  - https://github.com/conda-forge/ebooklib-feedstock/blob/main/recipe/meta.yaml

Not really sure how this all works but looking at the docs if you feel adventurous you might be able to update it also - https://conda-forge.org/#update_recipe

**Comment by thorgexyz** [comment] 2023-04-25 14:49
I am receiving this error on v.018 with the following [ebook](https://drive.google.com/file/d/1tJ0lcrnhFsl3fIgzGc9QZYN_w39t1J5s/view?usp=sharing)

Error:
KeyError: "There is no item named 'META-INF/container.xml' in the archive"

**Comment by LordFransie** [comment] 2024-05-06 18:44
I am also seeing this issue.
